import type { BusinessFlowProfileDefinition, BusinessFlowProfileId } from "@pos/domain/business-flows";

export const BUSINESS_FLOW_PROFILES: Record<BusinessFlowProfileId, BusinessFlowProfileDefinition> = {
  retail_standard: {
    id: "retail_standard",
    label: "Retail standard",
    description: "Direct cashier checkout for minimarket and store operations.",
    defaultFlowSummary: "Cart -> Pay -> Paid/Completed",
    uiSections: ["PRODUCT_GRID", "CART", "PAYMENT", "SERVER_DRAFTS", "LOCAL_DRAFTS", "RECEIPTS"],
    defaultActions: ["CREATE_AND_PAY", "CONTINUE_DRAFT", "UPDATE_DRAFT_ITEMS", "CANCEL_DRAFT", "VIEW_DRAFT", "VIEW_LOCAL_DRAFT", "DELETE_LOCAL_DRAFT"],
    optionalActions: ["SAVE_DRAFT", "REFUND_PAYMENT", "VOID_PAYMENT"],
    businessSpecificActions: [],
    coreActions: ["CREATE_AND_PAY", "SAVE_DRAFT", "CONTINUE_DRAFT", "UPDATE_DRAFT_ITEMS", "CANCEL_DRAFT"],
    notes: ["Kitchen, table service, and pay-later active orders are not default retail concepts."],
  },
  restaurant_table_service: {
    id: "restaurant_table_service",
    label: "Restaurant table service",
    description: "Table order flow with kitchen firing, served state, and later payment.",
    defaultFlowSummary: "Table/Cart -> Send to Kitchen -> Active Kitchen Order -> Served -> Pay",
    uiSections: ["PRODUCT_GRID", "CART", "PAYMENT", "SERVER_DRAFTS", "LOCAL_DRAFTS", "ACTIVE_ORDERS", "KITCHEN_QUEUE", "TABLES", "RECEIPTS"],
    defaultActions: ["SAVE_DRAFT", "CONTINUE_DRAFT", "UPDATE_DRAFT_ITEMS", "SEND_TO_KITCHEN", "PAY_ACTIVE_ORDER", "ADD_ITEM_TO_ACTIVE_ORDER", "VIEW_ACTIVE_ORDER", "VIEW_DRAFT", "VIEW_LOCAL_DRAFT"],
    optionalActions: ["CREATE_AND_PAY", "VOID_ITEM", "CANCEL_ACTIVE_ORDER", "SPLIT_BILL", "PARTIAL_PAYMENT"],
    businessSpecificActions: ["SEND_TO_KITCHEN", "PAY_ACTIVE_ORDER", "ADD_ITEM_TO_ACTIVE_ORDER", "VOID_ITEM", "CANCEL_ACTIVE_ORDER", "SPLIT_BILL"],
    coreActions: ["SAVE_DRAFT", "CONTINUE_DRAFT", "UPDATE_DRAFT_ITEMS", "PAY_ACTIVE_ORDER"],
    supportsPayFirstVariant: false,
    notes: ["Kitchen-fired items are locked from normal draft/cart editing.", "orders_queue is display capability, not a prerequisite for PAY_ACTIVE_ORDER."],
  },
  cafe_counter: {
    id: "cafe_counter",
    label: "Cafe counter",
    description: "Pay-first counter-service flow that may create preparation tickets after payment.",
    defaultFlowSummary: "Cart -> Pay -> Preparation/Kitchen Ticket -> Completed",
    uiSections: ["PRODUCT_GRID", "CART", "PAYMENT", "LOCAL_DRAFTS", "KITCHEN_QUEUE", "RECEIPTS"],
    defaultActions: ["CREATE_AND_PAY", "CREATE_PREPARATION_TICKET_AFTER_PAYMENT", "CONTINUE_DRAFT", "UPDATE_DRAFT_ITEMS", "VIEW_LOCAL_DRAFT"],
    optionalActions: ["SAVE_DRAFT", "REFUND_PAYMENT", "VOID_PAYMENT"],
    businessSpecificActions: ["CREATE_PREPARATION_TICKET_AFTER_PAYMENT"],
    coreActions: ["CREATE_AND_PAY", "SAVE_DRAFT", "CONTINUE_DRAFT", "UPDATE_DRAFT_ITEMS"],
    notes: ["No table requirement by default."],
  },
  quick_service: {
    id: "quick_service",
    label: "Quick service",
    description: "Fast pay-first flow with optional fulfillment queue.",
    defaultFlowSummary: "Cart -> Pay -> Fulfillment Queue/Preparation -> Complete",
    uiSections: ["PRODUCT_GRID", "CART", "PAYMENT", "ACTIVE_ORDERS", "RECEIPTS"],
    defaultActions: ["CREATE_AND_PAY", "REFUND_PAYMENT", "VOID_PAYMENT"],
    optionalActions: ["CREATE_PREPARATION_TICKET_AFTER_PAYMENT"],
    businessSpecificActions: ["CREATE_PREPARATION_TICKET_AFTER_PAYMENT"],
    coreActions: ["CREATE_AND_PAY"],
    notes: ["Queue-after-payment remains metadata only in P1."],
  },
  service_business_later: {
    id: "service_business_later",
    label: "Service business later",
    description: "Reserved placeholder for service orders with deposits and final payment.",
    defaultFlowSummary: "Service Order -> DP/Unpaid -> In Progress -> Done -> Final Payment",
    uiSections: ["PAYMENT", "RECEIPTS"],
    defaultActions: [],
    optionalActions: ["PARTIAL_PAYMENT", "PAY_ACTIVE_ORDER"],
    businessSpecificActions: [],
    coreActions: [],
    notes: ["Reserved for future P2+ workflow; complex actions disabled by default in P1."],
  },
};
