import { Request, Response } from 'express';
import { z } from 'zod';
import { container } from '../../../container';
import { asyncHandler, createError } from '../../middleware/errorHandler';
import { attachLifecycleFields } from './common';

function numberParam(defaultValue: number) { return z.string().optional().transform((val) => { if (!val) return defaultValue; const parsed = parseInt(val, 10); if (isNaN(parsed) || parsed < 0 || (defaultValue > 0 && parsed <= 0)) throw new Error('invalid number'); return parsed; }); }
export const listOpenOrders = asyncHandler(async (req: Request, res: Response) => { const tenantId = req.tenantId!; const parsed = z.object({ limit: numberParam(50), offset: numberParam(0) }).safeParse(req.query); if (!parsed.success) throw createError('Parameter pencarian pesanan tidak valid.',400,'VALIDATION_ERROR'); const result = await container.listOpenOrders.execute({ tenant_id: tenantId, outlet_id: req.outletId, limit: parsed.data.limit, offset: parsed.data.offset }); res.status(200).json({ success:true, data:{ orders: (await attachLifecycleFields(result.orders, tenantId)).filter((order) => order.lifecycleKind === 'server_draft' || order.lifecycleKind === 'active_order' || order.lifecycleKind === 'active_kitchen_order') } }); });
export const listOrderHistory = asyncHandler(async (req: Request, res: Response) => { const tenantId = req.tenantId!; const parsed = z.object({ limit: numberParam(20), offset: numberParam(0), from_date: z.string().datetime().optional().transform(v => v ? new Date(v) : undefined), to_date: z.string().datetime().optional().transform(v => v ? new Date(v) : undefined) }).safeParse(req.query); if (!parsed.success) throw createError('Parameter pencarian pesanan tidak valid.',400,'VALIDATION_ERROR'); const result = await container.listOrderHistory.execute({ tenant_id:tenantId, limit: parsed.data.limit, offset: parsed.data.offset, from_date: parsed.data.from_date, to_date: parsed.data.to_date, outlet_id: req.outletId }); res.status(200).json({ success:true, data:{ orders: await attachLifecycleFields(result.orders, tenantId), pagination: result.pagination } }); });
