import { Database } from '../../database';
import { BaseRepository } from '../BaseRepository';
import {
  paymentProviderEvents,
  type PaymentProviderEvent,
  type InsertPaymentProviderEvent,
} from '../../../../shared/schema';
import { and, eq, lt, sql } from 'drizzle-orm';

export interface IPaymentProviderEventRepository {
  /**
   * Insert a new provider event row.
   * Pass `tx` when called inside a db.transaction() to keep the operation atomic.
   */
  create(data: InsertPaymentProviderEvent, tx?: any): Promise<PaymentProviderEvent>;

  /**
   * Safe upsert: INSERT ... ON CONFLICT (provider, providerEventId) DO NOTHING RETURNING *.
   *
   * If the row was newly inserted, returns `{ event, created: true }`.
   * If the row already existed (unique conflict), fetches and returns `{ event, created: false }`.
   *
   * Key properties:
   * - Does NOT throw on duplicate providerEventId — safe to call inside or outside a DB transaction.
   * - ON CONFLICT DO NOTHING does not abort a PostgreSQL transaction (unlike a real constraint error).
   * - Uniqueness is global: (provider, providerEventId) is not tenant-scoped.
   *
   * Use this method instead of `create()` wherever idempotent event reservation is needed.
   */
  createOrGetByProviderEventId(
    data: InsertPaymentProviderEvent,
    tx?: any,
  ): Promise<{ event: PaymentProviderEvent; created: boolean }>;

  /**
   * Find an existing event by (provider, providerEventId).
   * The uniqueness is global — not scoped by tenant — because providerEventId is
   * generated by the external provider and is unique per provider.
   * Pass `tx` to read within an active transaction.
   */
  findByProviderEventId(
    provider: string,
    providerEventId: string,
    tx?: any,
  ): Promise<PaymentProviderEvent | null>;

  /**
   * Mark an event as successfully processed.
   * Sets processingStatus = 'processed' and processedAt = now().
   */
  markProcessed(id: string, data?: { processedAt?: Date }, tx?: any): Promise<PaymentProviderEvent>;

  /**
   * Mark an event as failed (e.g. transaction not found, DB error).
   * Sets processingStatus = 'failed' and errorMessage.
   */
  markFailed(id: string, errorMessage: string, tx?: any): Promise<PaymentProviderEvent>;

  /**
   * Mark an event as ignored (e.g. unsupported event type, TRANSACTION_ALREADY_TERMINAL).
   * Sets processingStatus = 'ignored' and errorMessage to the reason string.
   */
  markIgnored(id: string, reason: string, tx?: any): Promise<PaymentProviderEvent>;

  /**
   * Phase 5: List provider events stuck in 'pending' status older than cutoffDate.
   * Fresh events (created after cutoffDate) are never returned.
   * Optionally filtered by provider, tenantId, and limited by batchSize.
   *
   * Phase 5 Hardening: tenantId filter added so tenant-manager calls only see
   * their own events. null-tenant events are excluded when tenantId is provided.
   */
  listStalePendingEvents(
    cutoffDate: Date,
    options?: { provider?: string; tenantId?: string; limit?: number },
  ): Promise<PaymentProviderEvent[]>;

  /**
   * Phase 5 Hardening: Lock a provider event row by id with SELECT ... FOR UPDATE.
   * Must be called inside an active DB transaction.
   * Returns null if no row with that id exists.
   *
   * Used by ReprocessStaleProviderEvents to claim an event before processing,
   * preventing concurrent reconciliation jobs from double-processing the same event.
   */
  lockByIdForUpdate(id: string, tx: any): Promise<PaymentProviderEvent | null>;
}

export class PaymentProviderEventRepository
  extends BaseRepository<PaymentProviderEvent, InsertPaymentProviderEvent>
  implements IPaymentProviderEventRepository
{
  protected table = paymentProviderEvents;
  protected entityName = 'PaymentProviderEvent';

  constructor(db: Database) {
    super(db);
  }

  async create(data: InsertPaymentProviderEvent, tx?: any): Promise<PaymentProviderEvent> {
    try {
      const client = tx ?? this.db;
      const [result] = await client.insert(paymentProviderEvents).values(data).returning();
      return result;
    } catch (error) {
      this.handleError('create', error);
    }
  }

  /**
   * INSERT ... ON CONFLICT (provider, provider_event_id) DO NOTHING RETURNING *.
   *
   * When the row already exists the INSERT silently does nothing and returns an empty
   * array — PostgreSQL does NOT raise an error and does NOT abort the surrounding
   * transaction.  We then SELECT the existing row.
   *
   * This is safe to call inside an active DB transaction because:
   *   1. No unique-violation error is raised (the transaction stays active).
   *   2. The follow-up SELECT reads the committed row that caused the conflict.
   *
   * Calling with `tx` is supported but `tx` is not required — the method works
   * correctly on the bare database connection too (e.g. for invalid-signature audits
   * that must happen before any DB transaction is opened).
   */
  async createOrGetByProviderEventId(
    data: InsertPaymentProviderEvent,
    tx?: any,
  ): Promise<{ event: PaymentProviderEvent; created: boolean }> {
    try {
      const client = tx ?? this.db;

      // Attempt a silent INSERT. On unique conflict the statement produces zero rows.
      const insertedRows = await client
        .insert(paymentProviderEvents)
        .values(data)
        .onConflictDoNothing()
        .returning();

      if (insertedRows.length > 0) {
        return { event: insertedRows[0], created: true };
      }

      // Conflict — the row already exists. Fetch it safely.
      const existingRows = await client
        .select()
        .from(paymentProviderEvents)
        .where(
          and(
            eq(paymentProviderEvents.provider, data.provider),
            eq(paymentProviderEvents.providerEventId, data.providerEventId),
          ),
        )
        .limit(1);

      return { event: existingRows[0], created: false };
    } catch (error) {
      this.handleError('create or get by provider event id', error);
    }
  }

  async findByProviderEventId(
    provider: string,
    providerEventId: string,
    tx?: any,
  ): Promise<PaymentProviderEvent | null> {
    try {
      const client = tx ?? this.db;
      const rows = await client
        .select()
        .from(paymentProviderEvents)
        .where(
          and(
            eq(paymentProviderEvents.provider, provider),
            eq(paymentProviderEvents.providerEventId, providerEventId),
          ),
        )
        .limit(1);
      return rows[0] ?? null;
    } catch (error) {
      this.handleError('find by provider event id', error);
    }
  }

  async markProcessed(
    id: string,
    data?: { processedAt?: Date },
    tx?: any,
  ): Promise<PaymentProviderEvent> {
    try {
      const client = tx ?? this.db;
      const [result] = await client
        .update(paymentProviderEvents)
        .set({
          processingStatus: 'processed',
          processedAt: data?.processedAt ?? new Date(),
          errorMessage: null,
        })
        .where(eq(paymentProviderEvents.id, id))
        .returning();
      return result;
    } catch (error) {
      this.handleError('mark processed', error);
    }
  }

  async markFailed(id: string, errorMessage: string, tx?: any): Promise<PaymentProviderEvent> {
    try {
      const client = tx ?? this.db;
      const [result] = await client
        .update(paymentProviderEvents)
        .set({
          processingStatus: 'failed',
          errorMessage,
        })
        .where(eq(paymentProviderEvents.id, id))
        .returning();
      return result;
    } catch (error) {
      this.handleError('mark failed', error);
    }
  }

  async markIgnored(id: string, reason: string, tx?: any): Promise<PaymentProviderEvent> {
    try {
      const client = tx ?? this.db;
      const [result] = await client
        .update(paymentProviderEvents)
        .set({
          processingStatus: 'ignored',
          errorMessage: reason,
        })
        .where(eq(paymentProviderEvents.id, id))
        .returning();
      return result;
    } catch (error) {
      this.handleError('mark ignored', error);
    }
  }

  /**
   * Phase 5: Return provider events with processingStatus='pending' that were
   * created before cutoffDate (i.e. they are stale / orphaned).
   * Fresh events created at or after cutoffDate are excluded.
   * Results are ordered oldest-first so the oldest orphans are retried first.
   */
  async listStalePendingEvents(
    cutoffDate: Date,
    options?: { provider?: string; tenantId?: string; limit?: number },
  ): Promise<PaymentProviderEvent[]> {
    try {
      const conditions = [
        eq(paymentProviderEvents.processingStatus, 'pending'),
        lt(paymentProviderEvents.createdAt, cutoffDate),
      ] as any[];

      if (options?.provider) {
        conditions.push(eq(paymentProviderEvents.provider, options.provider));
      }

      // Phase 5 Hardening: tenant-scope filter.
      // When tenantId is supplied, only return rows that belong to that tenant.
      // Rows with tenantId = null are intentionally excluded — they require a
      // future superadmin/global reconciliation job, not a per-tenant manager call.
      if (options?.tenantId) {
        conditions.push(eq(paymentProviderEvents.tenantId, options.tenantId));
      }

      const rows = await this.db
        .select()
        .from(paymentProviderEvents)
        .where(and(...conditions))
        .orderBy(paymentProviderEvents.createdAt)
        .limit(options?.limit ?? 100);

      return rows;
    } catch (error) {
      this.handleError('list stale pending events', error);
    }
  }

  /**
   * Phase 5 Hardening: Lock a provider event row by id with SELECT ... FOR UPDATE.
   *
   * Must be called inside an active DB transaction (`tx` is required).
   * Returns null if no row with that id exists.
   *
   * Pattern mirrors PaymentTransactionRepository.lockByIdForUpdate — issue the
   * SELECT ... FOR UPDATE first to hold the advisory row lock, then re-fetch via
   * the ORM to get a fully-typed result object.
   */
  async lockByIdForUpdate(id: string, tx: any): Promise<PaymentProviderEvent | null> {
    try {
      await tx.execute(sql`
        SELECT id FROM payment_provider_events
        WHERE id = ${id}
        FOR UPDATE
      `);
      const rows = await tx
        .select()
        .from(paymentProviderEvents)
        .where(eq(paymentProviderEvents.id, id))
        .limit(1);
      return rows[0] ?? null;
    } catch (error) {
      this.handleError('lock by id for update', error);
    }
  }
}
