export const ENTITLEMENT_CATALOG = {
  meta: {
    version: 1,
    currency: 'IDR',
    description: 'Single source of truth for AuraPoS commercial tenant entitlements.',
  },
  billingIntervals: {
    none: { label: 'No billing interval' },
    one_time: { label: 'One time' },
    monthly: { label: 'Monthly' },
    yearly: { label: 'Yearly' },
  },
  plans: {
    starter: {
      label: 'Starter',
      sortOrder: 10,
      price: 0,
      billingInterval: 'monthly',
      included: [
        'inventory_basic_stock',
        'payments_cash',
        'payments_partial_payment',
        'receipt_standard',
        'receipt_reprint',
        'orders_open_order',
        'orders_queue',
        'catalog_products',
        'catalog_categories',
        'catalog_variants',
        'catalog_options',
        'reports_sales_basic',
        'reports_cashier',
        'hardware_receipt_printer',
      ],
    },
    growth: {
      label: 'Growth',
      sortOrder: 20,
      price: 99000,
      billingInterval: 'monthly',
      included: [
        'inventory_advanced_stock',
        'inventory_stock_adjustment',
        'inventory_stock_movement_history',
        'inventory_stock_opname',
        'inventory_low_stock_alert',
        'inventory_reports',
        'payments_manual_qris',
        'payments_manual_bank_transfer',
        'payments_multi_payment',
        'receipt_compact',
        'orders_cancel',
        'orders_void',
        'catalog_sku',
        'catalog_barcode',
        'restaurant_table_management',
        'restaurant_floor_layout',
        'restaurant_kitchen_ticket',
        'restaurant_kds',
        'restaurant_kitchen_printer',
        'reports_sales_advanced',
        'reports_inventory',
        'hardware_label_printer',
        'hardware_barcode_scanner',
        'hardware_cash_drawer',
        'integrations_accounting',
        'integrations_webhook',
      ],
    },
    pro: {
      label: 'Pro',
      sortOrder: 30,
      price: 199000,
      billingInterval: 'monthly',
      included: [
        'inventory_stock_transfer',
        'payments_split_payment',
        'orders_refund',
        'reports_export',
        'multi_location_outlets',
        'multi_location_stock',
        'multi_location_reports',
        'integrations_payment_gateway',
        'integrations_api_access',
      ],
    },
  },
  entitlements: {
    inventory_basic_stock: { label: 'Stok Dasar', kind: 'module', area: 'inventory' },
    inventory_advanced_stock: { label: 'Stok Lanjutan', kind: 'module', area: 'inventory' },
    inventory_stock_adjustment: { label: 'Penyesuaian Stok', kind: 'feature', area: 'inventory' },
    inventory_stock_movement_history: { label: 'Riwayat Pergerakan Stok', kind: 'feature', area: 'inventory' },
    inventory_stock_opname: { label: 'Stok Opname', kind: 'feature', area: 'inventory' },
    inventory_stock_transfer: { label: 'Transfer Stok', kind: 'feature', area: 'inventory' },
    inventory_low_stock_alert: { label: 'Peringatan Stok Menipis', kind: 'feature', area: 'inventory' },
    inventory_reports: { label: 'Laporan Inventaris', kind: 'feature', area: 'inventory' },
    payments_cash: { label: 'Pembayaran Tunai', kind: 'feature', area: 'payments' },
    payments_manual_qris: { label: 'QRIS Manual', kind: 'feature', area: 'payments' },
    payments_manual_bank_transfer: { label: 'Transfer Bank Manual', kind: 'feature', area: 'payments' },
    payments_partial_payment: { label: 'Pembayaran Sebagian', kind: 'feature', area: 'payments' },
    payments_multi_payment: { label: 'Multi Pembayaran', kind: 'feature', area: 'payments' },
    payments_split_payment: { label: 'Split Payment', kind: 'feature', area: 'payments' },
    receipt_standard: { label: 'Struk Standar', kind: 'feature', area: 'receipt' },
    receipt_reprint: { label: 'Cetak Ulang Struk', kind: 'feature', area: 'receipt' },
    receipt_compact: { label: 'Struk Ringkas', kind: 'feature', area: 'receipt' },
    orders_queue: { label: 'Antrian Order', kind: 'feature', area: 'orders' },
    orders_open_order: { label: 'Open Order', kind: 'feature', area: 'orders' },
    orders_cancel: { label: 'Batalkan Order', kind: 'feature', area: 'orders' },
    orders_void: { label: 'Void Order', kind: 'feature', area: 'orders' },
    orders_refund: { label: 'Refund Order', kind: 'feature', area: 'orders' },
    catalog_products: { label: 'Produk', kind: 'feature', area: 'catalog' },
    catalog_categories: { label: 'Kategori', kind: 'feature', area: 'catalog' },
    catalog_variants: { label: 'Varian Produk', kind: 'feature', area: 'catalog' },
    catalog_options: { label: 'Opsi Produk', kind: 'feature', area: 'catalog' },
    catalog_sku: { label: 'SKU', kind: 'feature', area: 'catalog' },
    catalog_barcode: { label: 'Barcode', kind: 'feature', area: 'catalog' },
    restaurant_table_management: { label: 'Manajemen Meja', kind: 'module', area: 'restaurant' },
    restaurant_floor_layout: { label: 'Layout Lantai', kind: 'feature', area: 'restaurant' },
    restaurant_kitchen_ticket: { label: 'Kitchen Ticket', kind: 'module', area: 'restaurant' },
    restaurant_kds: { label: 'Kitchen Display System', kind: 'feature', area: 'restaurant' },
    restaurant_kitchen_printer: { label: 'Printer Dapur', kind: 'feature', area: 'restaurant' },
    reports_sales_basic: { label: 'Laporan Penjualan Dasar', kind: 'feature', area: 'reports' },
    reports_sales_advanced: { label: 'Laporan Penjualan Lanjutan', kind: 'feature', area: 'reports' },
    reports_inventory: { label: 'Laporan Inventaris', kind: 'feature', area: 'reports' },
    reports_cashier: { label: 'Laporan Kasir', kind: 'feature', area: 'reports' },
    reports_export: { label: 'Ekspor Laporan', kind: 'feature', area: 'reports' },
    multi_location_outlets: { label: 'Multi Outlet', kind: 'module', area: 'multi_location' },
    multi_location_stock: { label: 'Stok Multi Outlet', kind: 'feature', area: 'multi_location' },
    multi_location_reports: { label: 'Laporan Multi Outlet', kind: 'feature', area: 'multi_location' },
    hardware_receipt_printer: { label: 'Printer Struk', kind: 'feature', area: 'hardware' },
    hardware_label_printer: { label: 'Printer Label', kind: 'feature', area: 'hardware' },
    hardware_barcode_scanner: { label: 'Scanner Barcode', kind: 'feature', area: 'hardware' },
    hardware_cash_drawer: { label: 'Cash Drawer', kind: 'feature', area: 'hardware' },
    integrations_payment_gateway: { label: 'Payment Gateway', kind: 'integration', area: 'integrations' },
    integrations_accounting: { label: 'Akuntansi', kind: 'integration', area: 'integrations' },
    integrations_webhook: { label: 'Webhook', kind: 'integration', area: 'integrations' },
    integrations_api_access: { label: 'API Access', kind: 'integration', area: 'integrations' },
  },
  offers: {
    receipt_compact_monthly: {
      entitlement: 'receipt_compact',
      requiredPlan: 'starter',
      price: 15000,
      billingInterval: 'monthly',
      expires: true,
    },
    orders_queue_addon: {
      entitlement: 'orders_queue',
      requiredPlan: 'growth',
      price: 25000,
      billingInterval: 'monthly',
      expires: true,
    },
    integrations_webhook_monthly: {
      entitlement: 'integrations_webhook',
      requiredPlan: 'growth',
      price: 49000,
      billingInterval: 'monthly',
      expires: true,
    },
  },
  businessTypes: {
    CAFE_RESTAURANT: {
      label: 'Cafe / Restaurant',
      defaultPlan: 'starter',
      defaultEntitlements: ['inventory_basic_stock', 'restaurant_table_management', 'restaurant_kitchen_ticket'],
      recommendedEntitlements: ['restaurant_kds', 'restaurant_kitchen_printer', 'receipt_compact', 'reports_sales_advanced'],
      orderTypes: ['DINE_IN', 'TAKE_AWAY', 'DELIVERY'],
      settings: { default_tax_rate: 0.1, default_service_charge_rate: 0.05, enable_tips: true },
    },
    RETAIL_MINIMARKET: {
      label: 'Retail / Minimarket',
      defaultPlan: 'starter',
      defaultEntitlements: ['inventory_basic_stock', 'catalog_barcode', 'hardware_barcode_scanner'],
      recommendedEntitlements: ['inventory_advanced_stock', 'inventory_low_stock_alert', 'reports_inventory'],
      orderTypes: ['WALK_IN'],
      settings: { default_tax_rate: 0.1, enable_barcode_scanner: false, low_stock_alert_enabled: false },
    },
    LAUNDRY: {
      label: 'Laundry',
      defaultPlan: 'starter',
      defaultEntitlements: ['inventory_basic_stock', 'hardware_label_printer'],
      recommendedEntitlements: ['orders_queue', 'receipt_compact', 'reports_sales_advanced'],
      orderTypes: ['WALK_IN'],
      settings: { default_tax_rate: 0.1, enable_item_tagging: false, default_turnaround_days: 3 },
    },
    SERVICE_APPOINTMENT: {
      label: 'Service / Appointment',
      defaultPlan: 'starter',
      defaultEntitlements: ['inventory_basic_stock', 'orders_open_order'],
      recommendedEntitlements: ['orders_queue', 'payments_partial_payment', 'reports_sales_advanced'],
      orderTypes: ['WALK_IN'],
      settings: { default_tax_rate: 0.1, appointment_duration_minutes: 60, booking_buffer_minutes: 15 },
    },
    DIGITAL_PPOB: {
      label: 'Digital / PPOB',
      defaultPlan: 'starter',
      defaultEntitlements: ['inventory_basic_stock', 'receipt_standard'],
      recommendedEntitlements: ['integrations_api_access', 'integrations_webhook', 'reports_sales_advanced'],
      orderTypes: ['WALK_IN'],
      settings: { enable_digital_receipts: true, auto_process_enabled: false },
    },
  },
} as const;

export type EntitlementCatalog = typeof ENTITLEMENT_CATALOG;
export type PlanCode = keyof EntitlementCatalog['plans'];
export type EntitlementCode = keyof EntitlementCatalog['entitlements'];
export type OfferCode = keyof EntitlementCatalog['offers'];
export type BusinessTypeCode = keyof EntitlementCatalog['businessTypes'];
export type BillingIntervalCode = keyof EntitlementCatalog['billingIntervals'];
